### PR TITLE
convivial-26950: Audience tasks.

### PR DESCRIPTION
**Pull request by radimklaska**
Mirrored from morpht/convivial-demo@78a5504 (26950).

### CODE REVIEW

**Comment by radimklaska** [comment]
Mirrored from morpht/convivial-demo@c4582ac (26950).

**Comment by radimklaska** [comment]
Mirrored from morpht/convivial-demo@06bfd2f (26950).

**Comment by radimklaska** [comment]
Mirrored from morpht/convivial-demo@f7f84f8 (26950).

**Comment by radimklaska** [comment]
Mirrored from morpht/convivial-demo@7307bda (26950).

**Comment by radimklaska** [comment]
Mirrored from morpht/convivial-demo@6c972b9 (26950).

**Comment by radimklaska** [comment]
Mirrored from morpht/convivial-demo@f646fa4 (26950).

**Review by abhisekmazumdar — APPROVED** [review]

**Pull request merged**
