### PR TITLE
convivial-demo-32853: Bootstrap `convivial_content` module.

### PR DESCRIPTION
**Pull request by radimklaska**
Mirrored from morpht/convivial-demo@c70eb21 (content).

### CODE REVIEW

**Comment by radimklaska** [comment]
Mirrored from morpht/convivial-demo@07c8a6a (content).

**Comment by radimklaska** [comment]
Mirrored from morpht/convivial-demo@7a48981 (content).

**Comment by radimklaska** [comment]
Mirrored from morpht/convivial-demo@65c0596 (content).

**Comment by radimklaska** [comment]
Mirrored from morpht/convivial-demo@816dde0 (content).

**Comment by abhisekmazumdar** [comment]
Closing as this is not required any more as a new PR is created: https://github.com/morpht/convivial-demo/pull/311

**Pull request closed without merging**
